### ISSUE TITLE
Disqus Viewing

### ISSUE THREAD

**Issue by LDigital84** [axiantheme/ghostion#5]
Is it possible to have Disqus load by default? (IE: Don't have to click a button). 

Thanks for the great theme!

**Comment by th3byrdm4n** [comment]
Yes and no.  Go to `partials > widgets > at_disqus.hbs`  That's where the comments code is...
Anyway the meat that makes the comments load is of course the button's code which boils down to:
`onclick="atPost.loadDisqus();return false;"`

You can just fire `atPost.loadDisqus();` at the bottom of the widget code, I suspect something like this would do it: 

``` javascript
<script>document.addEventListener('DOMContentLoaded', function(){
atPost.loadDisqus();
});
</script>
```
